### ISSUE TITLE
OperatingSystemHarverster fails if server only has one software package installed

### ISSUE THREAD

**Issue by erlendr** [condep/condep-dsl#6]
#### Version used:

Nuget package: `ConDep.Dsl` version `4.0.1` 
#### Log output:

```
[09:53:43] :                 [Collecting server data] OperatingSystemHarvester
[09:53:43] :                     [OperatingSystemHarvester] OperatingSystemHarvester
[09:53:43]E:     [Step 1/1] ConDep execution failed.
Message: Unable to cast object of type 'System.String' to type 'System.Collections.ArrayList'.

Stack Trace:
   at ConDep.Dsl.Harvesters.OperatingSystemHarvester.Harvest(ServerConfig server)
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.Remote.RemoteServerValidator.<>c__DisplayClass5.<IsValid>b__1()
   at ConDep.Dsl.Logging.Logger.WithLogSection(String sectionName, Action action)
   at ConDep.Dsl.Remote.RemoteServerValidator.<IsValid>b__0()
   at ConDep.Dsl.Logging.Logger.WithLogSection[T](String sectionName, Func`1 action)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.Validate(IValidateClient clientValidator, IValidateServer serverValidator)
   at ConDep.Dsl.Execution.ConDepConfigurationExecutor.Execute(ConDepSettings settings, IValidateClient clientValidator, IValidateServer serverValidator, ExecutionSequenceManager execManager, CancellationToken token)
```

I think it's this line of code: https://github.com/condep/condep-dsl/blob/master/src/ConDep.Dsl/Harvesters/OperatingSystemHarvester.cs#L84
#### How to reproduce:

Run deploy with a target server having only one package listed as installed. Target server OS is Windows Server 2012 R2.
#### Workaround:

Install a second package on target server before deploying again. :)

**Comment by torresdal** [comment]
You're right. For some strange reason PowerShell returns an array if items > 1 and a string if items == 1. I'll create a patch for this. Thanks for letting us know.

**Comment by brigs** [comment]
was this fixed @torresdal ? :)
